#!/usr/bin/env python3

"""
VaVAM 12g - Thor TensorRT + Euler Validation

Pipeline
--------
Pre-computed Visual Tokens
        |
        v
TensorRT JointModel
        |
        v
Action Velocity
        |
        v
Euler Integration x 10
        |
        v
Final Trajectory

Validation
----------
Compare Thor TensorRT + Euler results against
PC PyTorch reference generated by 12f.
"""

import os
import sys
from pathlib import Path

import numpy as np
import tensorrt as trt

from cuda.bindings import driver


# ============================================================================
# Paths
# ============================================================================

ROOT = Path.home() / "VideoActionModel"

ARTIFACT_DIR = (
    ROOT
    / "artifacts"
    / "vavam_joint"
)

ENGINE_PATH = (
    ARTIFACT_DIR
    / "vavam_joint_inference_step_fp32.engine"
)

INPUT_PATH = (
    ARTIFACT_DIR
    / "joint_reference.npz"
)

REFERENCE_PATH = (
    ARTIFACT_DIR
    / "thor_euler_reference.npz"
)


# ============================================================================
# Configuration
# ============================================================================

NUM_INFERENCE_STEPS = 10

DELTA_T = 1.0 / NUM_INFERENCE_STEPS


# ============================================================================
# CUDA helpers
# ============================================================================

def cuda_check(result, name):

    if isinstance(result, tuple):
        err = result[0]
    else:
        err = result

    if err != driver.CUresult.CUDA_SUCCESS:
        raise RuntimeError(
            f"{name} failed: {err}"
        )

    return result


def cuda_malloc(nbytes):

    result = driver.cuMemAlloc(
        int(nbytes)
    )

    cuda_check(
        result,
        "cuMemAlloc"
    )

    return result[1]


def cuda_free(ptr):

    if ptr is None:
        return

    result = driver.cuMemFree(
        ptr
    )

    cuda_check(
        result,
        "cuMemFree"
    )


def cuda_memcpy_htod(
    ptr,
    host_array,
):

    arr = np.ascontiguousarray(
        host_array
    )

    result = driver.cuMemcpyHtoD(
        int(ptr),
        arr,
        int(arr.nbytes),
    )

    cuda_check(
        result,
        "cuMemcpyHtoD"
    )


def cuda_memcpy_dtoh(
    host_array,
    ptr,
):

    arr = np.ascontiguousarray(
        host_array
    )

    result = driver.cuMemcpyDtoH(
        arr,
        int(ptr),
        int(arr.nbytes),
    )

    cuda_check(
        result,
        "cuMemcpyDtoH"
    )


def cuda_stream_create():

    result = driver.cuStreamCreate(0)

    cuda_check(
        result,
        "cuStreamCreate"
    )

    return result[1]


def cuda_stream_destroy(stream):

    if stream is None:
        return

    result = driver.cuStreamDestroy(
        stream
    )

    cuda_check(
        result,
        "cuStreamDestroy"
    )


def cuda_stream_sync(stream):

    result = driver.cuStreamSynchronize(
        stream
    )

    cuda_check(
        result,
        "cuStreamSynchronize"
    )


# ============================================================================
# Statistics
# ============================================================================

def stats(name, x):

    x = np.asarray(x)

    print()
    print(f"[{name}]")

    print(
        f"  shape : {x.shape}"
    )

    print(
        f"  dtype : {x.dtype}"
    )

    print(
        f"  min   : {x.min()}"
    )

    print(
        f"  max   : {x.max()}"
    )

    print(
        f"  mean  : {x.mean()}"
    )

    print(
        f"  std   : {x.std()}"
    )


def compare_arrays(
    reference,
    test,
):

    reference = np.asarray(
        reference,
        dtype=np.float32,
    )

    test = np.asarray(
        test,
        dtype=np.float32,
    )

    diff = np.abs(
        reference - test
    )

    max_abs = float(
        diff.max()
    )

    mean_abs = float(
        diff.mean()
    )

    rmse = float(
        np.sqrt(
            np.mean(
                (
                    reference - test
                ) ** 2
            )
        )
    )

    denom = np.maximum(
        np.abs(reference),
        1e-8,
    )

    max_rel = float(
        np.max(
            diff / denom
        )
    )

    return (
        max_abs,
        mean_abs,
        rmse,
        max_rel,
    )


# ============================================================================
# Load reference inputs
# ============================================================================

def load_inputs():

    print()
    print("=" * 80)
    print("Loading reference input")
    print("=" * 80)

    data = np.load(
        INPUT_PATH
    )

    visual_tokens = np.ascontiguousarray(
        data["visual_tokens"]
        .astype(np.int64)
    )

    high_level_command = np.ascontiguousarray(
        data["high_level_command"][
            :,
            :1,
        ].astype(np.int64)
    )

    # 12f reference contains:
    #
    # (1, 1, 6, 2)
    #
    # We use the first action state as Euler initial action.

    if "initial_action" in data:

        initial_action = np.ascontiguousarray(
            data["initial_action"][
                ...,
            ].astype(np.float32)
        )

    elif "noisy_actions" in data:

        initial_action = np.ascontiguousarray(
            data["noisy_actions"][
                :,
                :1,
                ...,
            ].astype(np.float32)
        )

    else:

        raise RuntimeError(
            "joint_reference.npz does not contain "
            "initial_action or noisy_actions"
        )

    if initial_action.shape == (
        1,
        8,
        6,
        2,
    ):

        initial_action = (
            initial_action[
                :,
                :1,
                ...,
            ]
        )

    print()
    print(
        f"  visual_tokens      : "
        f"{visual_tokens.shape} "
        f"{visual_tokens.dtype}"
    )

    print(
        f"  high_level_command : "
        f"{high_level_command.shape} "
        f"{high_level_command.dtype}"
    )

    print(
        f"  initial_action     : "
        f"{initial_action.shape} "
        f"{initial_action.dtype}"
    )

    return (
        visual_tokens,
        high_level_command,
        initial_action,
    )


# ============================================================================
# TensorRT engine
# ============================================================================

def load_engine():

    print()
    print("=" * 80)
    print("Loading TensorRT engine")
    print("=" * 80)

    logger = trt.Logger(
        trt.Logger.WARNING
    )

    runtime = trt.Runtime(
        logger
    )

    with open(
        ENGINE_PATH,
        "rb",
    ) as f:

        engine_data = f.read()

    engine = (
        runtime.deserialize_cuda_engine(
            engine_data
        )
    )

    if engine is None:

        raise RuntimeError(
            "Failed to deserialize TensorRT engine."
        )

    print()
    print(
        "[OK] TensorRT engine deserialized"
    )

    return (
        runtime,
        engine,
    )


def inspect_engine(engine):

    print()
    print(
        "[TRT] Engine I/O"
    )

    for i in range(
        engine.num_io_tensors
    ):

        name = (
            engine.get_tensor_name(i)
        )

        mode = (
            engine.get_tensor_mode(name)
        )

        dtype = (
            engine.get_tensor_dtype(name)
        )

        shape = tuple(
            engine.get_tensor_shape(name)
        )

        print()
        print(
            f"  {name}"
        )

        print(
            f"    mode  : {mode}"
        )

        print(
            f"    dtype : {dtype}"
        )

        print(
            f"    shape : {shape}"
        )


# ============================================================================
# One TensorRT inference step
# ============================================================================

def run_trt_step(
    engine,
    context,
    stream,
    allocations,
    host_outputs,
    visual_tokens,
    noisy_actions,
    high_level_command,
    diffusion_step,
):

    input_map = {

        "visual_tokens":
            visual_tokens,

        "noisy_actions":
            noisy_actions,

        "high_level_command":
            high_level_command,

        "diffusion_step":
            diffusion_step,
    }

    # ------------------------------------------------------------
    # H -> D
    # ------------------------------------------------------------

    for name, array in input_map.items():

        cuda_memcpy_htod(
            allocations[name],
            array,
        )

    # ------------------------------------------------------------
    # Set tensor addresses
    # ------------------------------------------------------------

    for name, ptr in allocations.items():

        ok = context.set_tensor_address(
            name,
            int(ptr),
        )

        if not ok:

            raise RuntimeError(
                f"Failed to set tensor address: "
                f"{name}"
            )

    # ------------------------------------------------------------
    # Execute
    # ------------------------------------------------------------

    ok = context.execute_async_v3(
        stream_handle=int(stream)
    )

    if not ok:

        raise RuntimeError(
            "TensorRT execute_async_v3 failed."
        )

    cuda_stream_sync(
        stream
    )

    # ------------------------------------------------------------
    # D -> H
    # ------------------------------------------------------------

    output = host_outputs[
        "action_velocity"
    ]

    cuda_memcpy_dtoh(
        output,
        allocations[
            "action_velocity"
        ],
    )

    return output.copy()


# ============================================================================
# Allocate TensorRT buffers
# ============================================================================

def allocate_buffers(engine):

    allocations = {}
    host_outputs = {}

    print()
    print(
        "[TRT] Allocating buffers..."
    )

    for i in range(
        engine.num_io_tensors
    ):

        name = (
            engine.get_tensor_name(i)
        )

        mode = (
            engine.get_tensor_mode(name)
        )

        dtype = (
            engine.get_tensor_dtype(name)
        )

        shape = tuple(
            engine.get_tensor_shape(name)
        )

        if any(
            d < 0
            for d in shape
        ):

            raise RuntimeError(
                f"Dynamic shape not supported: "
                f"{name} {shape}"
            )

        np_dtype = np.dtype(
            trt.nptype(dtype)
        )

        nbytes = (
            int(
                np.prod(shape)
            )
            * np_dtype.itemsize
        )

        allocations[name] = (
            cuda_malloc(nbytes)
        )

        if mode == trt.TensorIOMode.OUTPUT:

            host_outputs[name] = np.empty(
                shape,
                dtype=np_dtype,
            )

        print(
            f"  {name}: "
            f"dtype={np_dtype} "
            f"shape={shape} "
            f"nbytes={nbytes}"
        )

    return (
        allocations,
        host_outputs,
    )


# ============================================================================
# Euler integration
# ============================================================================

def run_euler(
    engine,
    visual_tokens,
    high_level_command,
    initial_action,
):

    print()
    print("=" * 80)
    print("Thor TensorRT + Euler Integration")
    print("=" * 80)

    context = (
        engine.create_execution_context()
    )

    if context is None:

        raise RuntimeError(
            "Failed to create execution context."
        )

    (
        allocations,
        host_outputs,
    ) = allocate_buffers(
        engine
    )

    stream = None

    velocity_history = []

    action_history = []

    # ------------------------------------------------------------
    # Current action
    # ------------------------------------------------------------

    action = np.ascontiguousarray(
        initial_action.copy()
        .astype(np.float32)
    )

    # Ensure inference shape
    if action.shape != (
        1,
        1,
        6,
        2,
    ):

        raise RuntimeError(
            "Unexpected initial action shape: "
            f"{action.shape}"
        )

    t = np.float32(
        0.0
    )

    action_history.append(
        action.copy()
    )

    print()
    print(
        f"  num_inference_steps : "
        f"{NUM_INFERENCE_STEPS}"
    )

    print(
        f"  delta_t             : "
        f"{DELTA_T}"
    )

    try:

        stream = cuda_stream_create()

        print()
        print(
            "[OK] CUDA stream created"
        )

        for step in range(
            NUM_INFERENCE_STEPS
        ):

            print()
            print(
                "-" * 80
            )

            print(
                f"Euler Step "
                f"{step + 1}/"
                f"{NUM_INFERENCE_STEPS}"
            )

            print(
                f"  t = {t:.6f}"
            )

            diffusion_step = np.ascontiguousarray(
                np.array(
                    [[t]],
                    dtype=np.float32,
                )
            )

            velocity = run_trt_step(
                engine,
                context,
                stream,
                allocations,
                host_outputs,
                visual_tokens,
                action,
                high_level_command,
                diffusion_step,
            )

            velocity_history.append(
                velocity.copy()
            )

            print()
            print(
                "[Velocity]"
            )

            print(
                f"  min   : "
                f"{velocity.min()}"
            )

            print(
                f"  max   : "
                f"{velocity.max()}"
            )

            print(
                f"  mean  : "
                f"{velocity.mean()}"
            )

            # ----------------------------------------------------
            # Euler update
            # ----------------------------------------------------

            action = np.ascontiguousarray(
                action
                + DELTA_T * velocity
            )

            action_history.append(
                action.copy()
            )

            print()
            print(
                "[Action after Euler update]"
            )

            print(
                f"  min   : "
                f"{action.min()}"
            )

            print(
                f"  max   : "
                f"{action.max()}"
            )

            print(
                f"  mean  : "
                f"{action.mean()}"
            )

            t = np.float32(
                t + DELTA_T
            )

    finally:

        if stream is not None:

            cuda_stream_sync(
                stream
            )

        for ptr in allocations.values():

            cuda_free(ptr)

        if stream is not None:

            cuda_stream_destroy(
                stream
            )

    velocity_history = np.stack(
        velocity_history,
        axis=0,
    )

    action_history = np.stack(
        action_history,
        axis=0,
    )

    final_trajectory = action.copy()

    return (
        velocity_history,
        action_history,
        final_trajectory,
    )


# ============================================================================
# Main
# ============================================================================

def main():

    print("=" * 80)
    print(
        "VaVAM 12g - Thor TensorRT + Euler Validation"
    )
    print("=" * 80)

    print()
    print("[Environment]")
    print(
        f"  TensorRT : {trt.__version__}"
    )

    # ------------------------------------------------------------
    # CUDA
    # ------------------------------------------------------------

    cuda_check(
        driver.cuInit(0),
        "cuInit"
    )

    device_result = (
        driver.cuDeviceGet(0)
    )

    cuda_check(
        device_result,
        "cuDeviceGet"
    )

    device = device_result[1]

    print(
        "[OK] CUDA Driver initialized"
    )

    # ------------------------------------------------------------
    # Check files
    # ------------------------------------------------------------

    print()
    print("[Files]")

    print(
        f"  engine    : {ENGINE_PATH}"
    )

    print(
        f"  input     : {INPUT_PATH}"
    )

    print(
        f"  reference : {REFERENCE_PATH}"
    )

    for path in (
        ENGINE_PATH,
        INPUT_PATH,
        REFERENCE_PATH,
    ):

        if not path.exists():

            raise FileNotFoundError(
                f"Missing file: {path}"
            )

    # ------------------------------------------------------------
    # Inputs
    # ------------------------------------------------------------

    (
        visual_tokens,
        high_level_command,
        initial_action,
    ) = load_inputs()

    # ------------------------------------------------------------
    # Engine
    # ------------------------------------------------------------

    (
        runtime,
        engine,
    ) = load_engine()

    inspect_engine(
        engine
    )

    # ------------------------------------------------------------
    # Euler
    # ------------------------------------------------------------

    (
        velocity_history,
        action_history,
        final_trajectory,
    ) = run_euler(
        engine,
        visual_tokens,
        high_level_command,
        initial_action,
    )

    # ------------------------------------------------------------
    # Statistics
    # ------------------------------------------------------------

    stats(
        "Thor velocity_history",
        velocity_history,
    )

    stats(
        "Thor final_trajectory",
        final_trajectory,
    )

    # ------------------------------------------------------------
    # Load PC reference
    # ------------------------------------------------------------

    print()
    print("=" * 80)
    print("Loading PC Euler reference")
    print("=" * 80)

    ref = np.load(
        REFERENCE_PATH
    )

    ref_velocity = ref[
        "velocity_history"
    ]

    ref_action = ref[
        "action_history"
    ]

    ref_final = ref[
        "final_trajectory"
    ]

    print()
    print(
        f"  reference velocity_history : "
        f"{ref_velocity.shape}"
    )

    print(
        f"  reference action_history   : "
        f"{ref_action.shape}"
    )

    print(
        f"  reference final_trajectory : "
        f"{ref_final.shape}"
    )

    # ------------------------------------------------------------
    # Compare velocity history
    # ------------------------------------------------------------

    print()
    print("=" * 80)
    print("Velocity History Comparison")
    print("=" * 80)

    velocity_pass = True

    for i in range(
        NUM_INFERENCE_STEPS
    ):

        (
            max_abs,
            mean_abs,
            rmse,
            max_rel,
        ) = compare_arrays(
            ref_velocity[i],
            velocity_history[i],
        )

        print()
        print(
            f"Euler Step {i + 1}"
        )

        print(
            f"  max abs error : "
            f"{max_abs:.10e}"
        )

        print(
            f"  mean abs error: "
            f"{mean_abs:.10e}"
        )

        print(
            f"  RMSE          : "
            f"{rmse:.10e}"
        )

        print(
            f"  max rel error : "
            f"{max_rel:.10e}"
        )

        if max_abs > 1e-4:

            velocity_pass = False

            print(
                "  [FAIL]"
            )

        else:

            print(
                "  [PASS]"
            )

    # ------------------------------------------------------------
    # Compare action history
    # ------------------------------------------------------------

    print()
    print("=" * 80)
    print("Action History Comparison")
    print("=" * 80)

    action_pass = True

    for i in range(
        11
    ):

        (
            max_abs,
            mean_abs,
            rmse,
            max_rel,
        ) = compare_arrays(
            ref_action[i],
            action_history[i],
        )

        print()
        print(
            f"Action State {i}"
        )

        print(
            f"  max abs error : "
            f"{max_abs:.10e}"
        )

        print(
            f"  mean abs error: "
            f"{mean_abs:.10e}"
        )

        print(
            f"  RMSE          : "
            f"{rmse:.10e}"
        )

        print(
            f"  max rel error : "
            f"{max_rel:.10e}"
        )

        if max_abs > 1e-4:

            action_pass = False

            print(
                "  [FAIL]"
            )

        else:

            print(
                "  [PASS]"
            )

    # ------------------------------------------------------------
    # Final trajectory
    # ------------------------------------------------------------

    print()
    print("=" * 80)
    print("Final Trajectory Comparison")
    print("=" * 80)

    (
        final_max_abs,
        final_mean_abs,
        final_rmse,
        final_max_rel,
    ) = compare_arrays(
        ref_final,
        final_trajectory,
    )

    print()
    print(
        f"  max abs error : "
        f"{final_max_abs:.10e}"
    )

    print(
        f"  mean abs error: "
        f"{final_mean_abs:.10e}"
    )

    print(
        f"  RMSE          : "
        f"{final_rmse:.10e}"
    )

    print(
        f"  max rel error : "
        f"{final_max_rel:.10e}"
    )

    final_pass = (
        final_max_abs <= 1e-4
    )

    if final_pass:

        print()
        print(
            "[PASS] Final trajectory matches."
        )

    else:

        print()
        print(
            "[FAIL] Final trajectory mismatch."
        )

    # ------------------------------------------------------------
    # Save Thor result
    # ------------------------------------------------------------

    output_path = (
        ARTIFACT_DIR
        / "thor_trt_euler_result.npz"
    )

    np.savez(
        output_path,
        velocity_history=velocity_history,
        action_history=action_history,
        final_trajectory=final_trajectory,
    )

    print()
    print("=" * 80)
    print("12g RESULT")
    print("=" * 80)

    print()
    print(
        f"  result : {output_path}"
    )

    print()

    if (
        velocity_pass
        and action_pass
        and final_pass
    ):

        print(
            "[PASS] Thor TensorRT + Euler "
            "matches PC PyTorch reference."
        )

        print()
        print(
            "Pipeline verified:"
        )

        print(
            "  Visual Tokens"
        )

        print(
            "       ↓"
        )

        print(
            "  TensorRT JointModel"
        )

        print(
            "       ↓"
        )

        print(
            "  Euler × 10"
        )

        print(
            "       ↓"
        )

        print(
            "  Trajectory"
        )

        return 0

    print(
        "[FAIL] Thor TensorRT + Euler "
        "does not match reference."
    )

    return 1


if __name__ == "__main__":

    sys.exit(
        main()
    )